- operator/controllers/keda_controller_test.go
- operator/controllers/suite_test.go
- operator/controllers/testdata/.helmignore
- operator/controllers/testdata/Chart.yaml
- operator/controllers/testdata/templates/01-serviceaccount.yaml
- operator/controllers/testdata/templates/_helpers.tpl
- operator/controllers/testdata/values.yaml
- Add basic scaffold for operator tests
See also: https://github.com/kyma-project/keda-manager/issues/4
> Add basic scaffold for operator tests

- operator/Makefile
- Change default image name
See also: https://github.com/kyma-project/keda-manager/issues/5
> Change default image name

- operator/.dockerignore
- operator/Dockerfile
- add layer containing keda chart
- optimize image layers 
See also: https://github.com/kyma-project/keda-manager/issues/5
> Fix operator Dockerfile

- operator/api/v1alpha1/keda_types.go
- operator/api/v1alpha1/zz_generated.deepcopy.go
- operator/config/crd/bases/operator.kyma-project.io_kedas.yaml
- fix metrics server log level type
> fix metrics server log level type

- operator/api/v1alpha1/keda_types.go
- operator/config/crd/bases/operator.kyma-project.io_kedas.yaml
- fix typo in metrics server configuration
> fix typo in metrics server configuration

- operator/api/v1alpha1/keda_types.go
- operator/config/crd/bases/operator.kyma-project.io_kedas.yaml
- operator/controllers/keda_controller_test.go
- add next test steps
See also #4
> add next test steps

- operator/controllers/keda_controller_test.go
- add check if keda is deleted or deleting after deletion
See also #4
> add check if keda is deleted or deleting after deletion

- README.md
> change title in the readme

- operator/Makefile
- fix makefile to accept image name passed via env variable
See also: https://github.com/kyma-project/keda-manager/issues/16
> Fix makefile to accept image name passed via env variable

- README.md
- change the Deploy header to another instruction step
> change header to another step

- README.md
Fixes https://github.com/kyma-project/keda-manager/issues/32
> Describe Keda Module installation on k3d

- Makefile
> fix kustomize download

- Makefile
- hack/get_kyma_file_name.sh
- fix kyma-cli download to detect os type and architecture
> fix kyma cli download

- Makefile
- update `Makefile` to use changed kyma alpha create module API
> Update Makefile to use changed kyma cli API

- operator/controllers/keda_controller_test.go
- operator/controllers/suite_test.go
- operator/go.mod
- operator/go.sum
> Update ginkgo to v2

- operator/Dockerfile
- operator/config/default/kustomization.yaml
- operator/config/manager/manager.yaml
- operator/config/ui-extensions/kustomization.yaml
- operator/config/ui-extensions/scaledobjects/details
- operator/config/ui-extensions/scaledobjects/form
- operator/config/ui-extensions/scaledobjects/general
- operator/config/ui-extensions/scaledobjects/kustomization.yaml
- operator/config/ui-extensions/scaledobjects/list
- operator/config/ui-extensions/scaledobjects/presets
- operator/controllers/keda_controller.go
- operator/module-chart/manifest/manifest.yaml
- add UI extension for Keda's scaled objects
https://github.com/kyma-project/keda-manager/issues/36
> Add UI Extension for scaledObjects CRs

- .gitignore
- README.md
- deploy-kyma-keda-k3d.sh
- k3d-patches/busola-extensibility.yaml
- k3d-patches/busola-kyma-extension.yaml
- k3d-patches/patch-k3d-coredns.yaml
- k3d-patches/patch-k3d-module-manager-clusterrole.yaml
- k3d-patches/patch-kyma.yaml
- Script steps for deploying keda to modular kyma on k3d
> Introduce script for automated deployment on k3d

- README.md
> Describe hack make target in readme

- hack/local/keda/k3d-patches/patch-kyma.yaml
- Update template channel for local development
> Update template channel for local development

- Makefile
- hack/ci/Makefile
- Add recipes to build module on CI job
See also:
- https://github.com/kyma-project/keda-manager/issues/58
> Add recipes to build module on CI job

- Makefile
- hack/ci/Makefile
- fix args passing in ci script
> fix args passing in ci script

- .env
- Makefile
- hack/ci/Makefile
- Improve ci script to handle MODULE_VERSION
> Improve ci script

- hack/ci/Makefile
This is to rebuild the post-submit jobs
> Add frame for printed template

- README.md
- hack/local/keda/Makefile
- Improve the Keda README.md file based on the recent changes in Serverless README.md
Resolves #67
> improve Keda README.md

- CODEOWNERS
- OWNERS_ALIASES
- Add nataliasitko to CODEOWNERS and OWNERS_ALIASES
- Remove majakurcius from CODEOWNERS and OWNERS_ALIASES
- https://github.com/kyma-project/kyma/issues/16151
- https://github.com/kyma-project/kyma/issues/16378
> Edit codeowners

- config/ui-extensions/scaledobjects/form
- make sure `ApiVersion` is autofilled based on `Kind` selection
- render reference editor based on selected `Kind`
> Make use of busola dynamic form rendering

- Makefile
- cleanup unused make target
Fixes https://github.com/kyma-project/keda-manager/issues/54
> Remove module-template-push target

- api/v1alpha1/keda_types.go
- config/default/kustomization.yaml
- config/manager/kustomization.yaml
- pkg/reconciler/initialize.go
- Remove initializing status state
> Remove initializing status state

- Makefile
- hack/ci/Makefile
- add mock for integration tests to add the possibility to work on tests and test-infra at the same time
https://github.com/kyma-project/keda-manager/pull/85
> Add integration-test mock

- CODEOWNERS
This pr will add MK to code owners so that I will be able to do review.
- Add MK to the code owners
> Add MK to codeowners

- Makefile
- Introduce make targets stubs to be used in e2e  release process and module submission process
https://github.com/kyma-project/kyma/issues/16494
> Introduce stubs for make targets composing E2E release process

- config/ui-extensions/scaledobjects/form
- config/ui-extensions/scaledobjects/general
- fix configuration for `scaledTargetRef.apiversion`
> Fix api versions for scaled object targets in the Form view

- README.md
- api/v1alpha1/keda_types.go
- pkg/reconciler/common.go
- pkg/reconciler/delete_resources.go
- pkg/reconciler/delete_resources_test.go
- pkg/reconciler/initialize.go
- pkg/reconciler/update_objects.go
- pkg/reconciler/verify.go
- propose new safe strategy version
- update documentaion
https://github.com/kyma-project/keda-manager/issues/89
> Implement safe deletion strategy

- Makefile
- config/manager/kustomization.yaml
- config/moduletemplates/kustomization.yaml
- hack/ci/Makefile
- hack/local/keda/Makefile
Updating targets installing Keda to reflect new CLI changes
> Update Makefile to reflect new CLI changes

- .gitignore
- config/ui-extensions/scaledobjects/form
- Fix scaledObjectTerget referernce editor
> Fix scaledObjectTerget referernce editor

- Makefile
- README.md
- config/samples/operator_v1alpha1_keda.yaml
- docs/installation-on-k3d.md
- hack/local/keda/k3d-patches/patch-kyma.yaml
- reduce resources of keda workloads
- change default log level to info
- change the default release channel
> Adjust sample keda CR

- README.md
- change make targets to the right one after refactoring ( [here](https://github.com/kyma-project/keda-manager/pull/112) )
https://github.com/kyma-project/keda-manager/issues/110
> update makefile targets in doc

- .env
> Bump keda module version to 0.0.2

- hack/ci/Makefile
- hack/common/Makefile
Removes a hack related to old CLI requirements.
> Moving upgrade logic to Keda Repo

- .env
- config/default/kustomization.yaml
- config/manager/kustomization.yaml
- hack/common/Makefile
> Bump version v0.0.3

- sec-scanners-config.yaml
Adds a security config to enable security scans for Keda Manager.
https://github.com/kyma-project/keda-manager/issues/10
> Add Security Config to Keda Manager

- hack/ci/Makefile
- hack/common/Makefile
Because of a flaw in test logic we didnt print the template in post jobs.
Adds a print that will show the keda template on a post job.
> Add priting to make target

- pkg/reconciler/emmit_event.go
- pkg/reconciler/update_status.go
- improve event message
- fix the typo in the function name
> Improve events message

- api/v1alpha1/keda_types.go
- pkg/reconciler/delete_resources.go
- pkg/reconciler/delete_resources_test.go
- pkg/reconciler/emmit_event.go
> Don't update condition while keda CR is deleted

- .env
- config/default/kustomization.yaml
- config/manager/kustomization.yaml
- hack/common/Makefile
- bump module version env and default tag
> Bumpe version to v0.0.4

- hack/common/Makefile
- Keda module template should have beta label
> Add beta label to test keda as beta module

- .env
- config/manager/kustomization.yaml
- keda.yaml
- sec-scanners-config.yaml
- Use latest patch version of keda
> Bump Keda version to 2.10.1

- .github/workflows/create-release.yaml
- .github/workflows/run-unit-tests-reusable.yaml
- scripts/await_artifacts.sh
- scripts/create_changelog.sh
- scripts/create_draft_release.sh
- scripts/publish_release.sh
- scripts/release.sh
Implement automated release flow
- Add release script
- Add changelog script
- Add run unit tests script
**Waits for** 
https://github.com/kyma-project/test-infra/pull/7714
> GitHub actions release

- .env
- config/manager/kustomization.yaml
> Bump Version before Release

- .github/workflows/create-release.yaml
Changes step name in both places
> Fix step name for Actions

- scripts/release.sh
Changes the command used to build the module
> Build module for release process

- scripts/release.sh
> Change command used for release

- .github/workflows/create-release.yaml
- Add script for creating assets
> Add script for creating assets

- .github/workflows/create-release.yaml
> Fix release_id variable

- scripts/await_artifacts.sh
- scripts/release.sh
- Wait for `keda-manager.yaml`
- Cat `keda-manager.yaml` in `release.sh`
> Wait for keda-manager.yaml

- sec-scanners-config.yaml
Bump keda-manager image in sec scanner config
> Bump keda-manager image in sec scanner config

- api/v1alpha1/keda_types.go
- config/rbac/role.yaml
- controllers/keda_controller_rbacs.go
- pkg/reconciler/delete_resources.go
- pkg/reconciler/delete_resources_test.go
- pkg/reconciler/emmit_event.go
- pkg/reconciler/fsm.go
- add "Deleted" condition
- do not emit events on deletion
See also #180
> add deleted condition

- hack/ci/Makefile
- move changes from the serverless-manager ( [PR](https://github.com/kyma-project/serverless-manager/pull/114) )
> Remove keda after integration test finish

- go.mod
> Run Tidy on Gomod

- .github/workflows/run-unit-tests-reusable.yaml
> Bump go version in workflow

- docs/user/05-01-conditions.md
- Add doc on Keda's conditions
Fixes #183
> Add document on Keda conditions

- scripts/release.sh
> Release script clean up

- scripts/release.sh
Move tests to a separate job and separate script
> Move tests to separate file outside of release.sh

- .env
- config/manager/kustomization.yaml
- bump keda-manager version before release
> Bump keda-manager version

- .github/workflows/create-release.yaml
> Add a checkout step for verify action

- scripts/verify-keda-status.sh
- Added a message to enable debugging
> Add debug message to verify step in GH actions

- scripts/verify-keda-status.sh
- Github's token isnt enough, using secret access token instead
- ...
- ...
> Change credentials used in github actions

- .github/workflows/create-release.yaml
- scripts/verify-keda-status.sh
- Removed a token from script
- ...
- ...
> Removed token from workflow

- sec-scanners-config.yaml
- Fix configuration of exclude folders list for Mend scans
> Fix Mend exclude field in sec config

- sec-scanners-config.yaml
As in title
- Updated security scanner config
> Updated the security scanner config to include newest release

- docs/contributor/02-10-management.md
- fix link for demo applications
> fix demo applications link

- .env
- config/manager/kustomization.yaml
> Prepare for Keda Patch

- pkg/annotation/disclaimer.go
- pkg/annotation/disclaimer_test.go
- pkg/reconciler/apply.go
- add DO NOT EDIT disclaimer
https://github.com/kyma-project/serverless-manager/issues/113
> Implement disclaimer for all applied objects

- sec-scanners-config.yaml
- bump image in security-config
https://github.com/kyma-project/keda-manager/issues/223
> Bump image 

- hack/common/Makefile
- mute the gcloud command
https://github.com/kyma-project/keda-manager/issues/210
> Prepare makefiles for new test-infra dind image

- .env
- trigger job
https://github.com/kyma-project/keda-manager/issues/223
> Trigger post module build

- scripts/check_image.sh
- sec-scanners-config.yaml
- use newest tag
- fix check image script
https://github.com/kyma-project/keda-manager/issues/227
> Bump image and fix image checker

- docs/user/04-20-demo-applications.md
- Fix broken links
- https://github.com/kyma-project/kyma/issues/17805
> fix broken links

- scripts/check_release_tag.sh
- sec-scanners-config.yaml
- Bump image
- improve error message
https://github.com/kyma-project/keda-manager/issues/227
> Improve err msg and bump image

- config/ui-extensions/kedas/details
- config/ui-extensions/kedas/form
- config/ui-extensions/kedas/general
- config/ui-extensions/kedas/kustomization.yaml
- config/ui-extensions/kedas/list
- config/ui-extensions/kustomization.yaml
- Configure UI for KEda CR so that user can inspect and edit configuration
> Configure UI for Keda CR

- keda.yaml
- sec-scanners-config.yaml
- Use latest keda version (v2.11.1)
https://github.com/kyma-project/keda-manager/issues/237
> Bump keda version (v2.11.1)

- sec-scanners-config.yaml
- use latest keda-manager image in security scanner config
> Upgate sec-scanner-config

- controllers/suite_test.go
Speed up tests
- before changes
```
ok      github.com/kyma-project/keda-manager/controllers        81.831s coverage: 55.0% of statements
```
- after changes
```
ok      github.com/kyma-project/keda-manager/controllers        23.226s coverage: 55.0% of statements
```
- Speed up tests
> speed up tests

- hack/common/Makefile
Remove labels to simplify test case
> Remove Labels

- scripts/release.sh
> Add template to release assets

- sec-scanners-config.yaml
> Update security scanner exclusions

- sec-scanners-config.yaml
- bump keda images in security scanners config
#269
> Bump keda module images in security context

- .github/workflows/create-release.yaml
- scripts/check_image.sh
- scripts/create_changelog.sh
- scripts/verify-keda-status.sh
- move changes proposed in the serverless-manager release workflow (refactor) to the keda-manager 
https://github.com/kyma-project/serverless-manager/issues/186
https://github.com/kyma-project/serverless-manager/pull/246
https://github.com/kyma-project/serverless-manager/pull/255
> Refactor release workflow

- sec-scanners-config.yaml
> Bump keda module images in security context2

- .github/workflows/metrics.yaml
- sec-scanners-config.yaml
> Revert metrics changes

- .github/workflows/metrics.yaml
- sec-scanners-config.yaml
- bump keda-manager image.. again
- bring back valid gh action name
> Revert action name

- sec-scanners-config.yaml
- bump image to incluge golang version (1.21.0) update
#280
> Bump keda menager in security config

- sec-scanners-config.yaml
> Bump versions in security config

- .gitignore
- Makefile
- module-config-template.yaml
https://github.com/kyma-project/keda-manager/issues/267
> Implement module-config template

- .github/workflows/create-release.yaml
- .github/workflows/metrics.yaml
> Restore dora step

- hack/get_kyma_file_name.sh
- allow to download darwin arm kyma cli
> Add darwin arm to script

- sec-scanners-config.yaml
> Sec Scanner Config Bump

- Makefile
- Align fqdn of keda module with the name used at the submission pipeline
> Unify fqdn for keda module

- .github/workflows/create-release.yaml
- scripts/check_image.sh
Updated to match the image in new sec_scanner_config and make releasing easier
https://github.com/kyma-project/keda-manager/issues/287
> Change workflow to match Sec_scanner_config with new release version

- Dockerfile
> Bump golang

- sec-scanners-config.yaml
> Bump image

- sec-scanners-config.yaml
> Use correct tag for release

- scripts/release.sh
> Add more release logs

- config/manager/kustomization.yaml
- sec-scanners-config.yaml
- Include tag 1.0.0 is sec scanning
> Include version 1.0.0 in scanning

- sec-scanners-config.yaml
> Use latest tags in sec-scanners-config on main

- Makefile
- scripts/release.sh
- sec-scanners-config-local.yaml
- Use sec-scanners-config during the release 
- Remove sec-scanners-config-local
https://github.com/kyma-project/serverless/issues/411
> Use sec-scanners-config during the release 

- .golangci.yaml
- add configuration for golangci-lint
> add configuration for golangci-lint

- sec-scanners-config.yaml
> Bump keda-manager in security scanners conf

- sec-scanners-config.yaml
https://github.com/kyma-project/test-infra/pull/9427
> Use branch name instead of latest word

- config/manager/kustomization.yaml
- hack/ci/Makefile
- hack/common/Makefile
- Cherry-Pick change described [here](https://github.com/kyma-project/serverless/pull/465/files)
> Exclude module-manifest from keda upgrade test scenario

- .github/workflows/daily-markdown-link-check.yaml
- .github/workflows/pr-markdown-link-check.yaml
- mlc.config.json
- Enable Markdown Link Check in the keda manager repo
Resolves #321
> Enable Markdown Link Check in the keda manager repo

- CODE_OF_CONDUCT.md
- README.md
- docs/contributor/01-20-extend-ui.md
- Fix links in keda manager repo
> Fix links in keda manager repo

- docs/user/04-20-demo-applications.md
- Fix bug in Demo Applications
> Fix bug in Demo Applications

- .github/scripts/upgrade-sec-scanners-config.sh
- .github/workflows/create-release.yaml
- add a job that will bump all main images in the `sec-scanners-config.yaml`
- https://github.com/kyma-project/keda-manager/issues/339
> Automatic bump in sec-scanners-config in the release process

- Dockerfile
> Bump golang to 1.21.5

- .github/scripts/verify-keda-jobs-status.sh
- use the build-in tool to verify jobs, to use GITHUB_TOKEN, and to not reach request limits after a few requests
- https://github.com/kyma-project/keda-manager/issues/339
> Use the `gh-cli` app to verify job statuses

- .github/workflows/create-release.yaml
- add a token to use the `gh` command
- https://github.com/kyma-project/keda-manager/issues/339
> Add missing `GH_TOKEN` env

- README.md
> Move status badge to status subcategory

- .github/workflows/keda-verify.yml
- Enable linting in GH Actions
> Enable linting in GH Actions

- .github/workflows/keda-verify.yml
- Enable unit tests in GH Actions
> Enable unit tests in GH Actions

- .github/workflows/keda-verify.yml
- config/manager/kustomization.yaml
- hack/ci/Makefile
- Enable upgrade test in GH Actions
> Enable upgrade tests in GH Actions

- .github/dependabot.yml
- enable dependabot for actions & dockerfile
> enable dependabot for actions & dockerfile

- .github/workflows/keda-verify.yml
- hack/ci/Makefile
- hack/common/Makefile
- Enable integration tests in GH Actions
> Enable integration tests in GH Actions

- .github/workflows/keda-verify.yml
> Fix upgrade GH Action

- hack/ci/Makefile
- hack/common/Makefile
- Don't fail on namespace creation
> Don't fail on namespace creation

- docs/contributor/01-10-installation.md
- Remove links to non-existing sections detected during testing the custom link check
> Remove links to non-existing sections

- hack/common/Makefile
As in title
**Note**
`.PHONY: verify-kyma` left untouched as its probably going to be deleted soon
> Add resources check to keda jobs

- hack/ci/Makefile
- hack/common/Makefile
- hack/local/Makefile
Remove makefile targets with lifecycle manager
See also #362
> remove makefile targets with lifecycle manager

- hack/ci/Makefile
- hack/common/Makefile
- hack/local/Makefile
rename makefile targets "without lm"
See also #362
> rename makefile targets "without lm"

- .github/workflows/keda-verify.yml
- Run integration tests on k8s v1.28
https://github.tools.sap/kyma/backlog/issues/5057
> Test keda module on k8s 1.28.6

- docs/contributor/01-10-installation.md
- docs/contributor/02-10-management.md
- docs/contributor/04-10-ci-cd.md
- Change on cluster to in cluster
https://github.com/kyma-project/kyma/issues/18581
> Change on cluster to in cluster

- docs/contributor/04-10-ci-cd.md
- Improve the testing strategy doc
Fixes #370
> Improve the Keda module testing strategy doc

- config/rbac/role.yaml
- controllers/keda_controller_rbacs.go
- keda.yaml
- sec-scanners-config.yaml
- use latest keda version
#383
> chore: Bump Keda to 2.13.1

- .github/dependabot.yml
- .github/workflows/keda-verify.yml
- Fix failing workflow
- disable dependabot for actions
- #387
> Fix failing workflow

- Makefile
- change the default IMG value used to render manifest, image build & push, as well as deployment. 
- #385
> Fix release image path

- .github/workflows/keda-verify.yml
- go.mod
- go.sum
- pkg/reconciler/served_filter_test.go
- bump go version to `1.22`
- https://github.com/kyma-project/keda-manager/issues/395
> Upgrade project go version

- CODEOWNERS
> Add Halamix2 to codeowners

- .github/scripts/release.sh
- .github/workflows/create-release.yaml
- add missing space
- add missing BOT_TOKEN
- https://github.com/kyma-project/warden/issues/180
> Remove differences between keda-manager and serverless repos

- mlc.config.json
- https://github.com/kyma-project/serverless/issues/848#issue-2222275134
> Disable md checks for shields and reuse links

- .github/workflows/keda-verify.yml
- Upgrading k8s in tests due to planned K8s Upgrade (from v.1.28 to v.1.29) in managed kyma runtime
> Test with k8s v1.29.3

- Dockerfile
- To avoid conflict in dockerfiles we need to use a name other than "workspace"
- https://github.com/kyma-project/serverless/pull/919
> fix image building under ADO

- .github/actions/rebase/action.yaml
- .github/workflows/daily-markdown-link-check.yaml
- .github/workflows/keda-verify.yml
- .github/workflows/pr-markdown-link-check.yaml
- .github/workflows/pull-gitleaks.yaml
- propose the `rebase` action
- implement new action in all `pre` jobs
- https://github.com/kyma-project/serverless/issues/971
> Create  the `rebase` action

- .github/workflows/integration-tests.yaml
- docs/contributor/04-10-testing-strategy.md
> adjust testing strategy

- config/ui-extensions/kedas/general
- Unify Keda CR's description to be consistent with all CR descriptions in Kyma dashboard
https://github.com/kyma-project/kyma/issues/18321
> Unify Keda CR description in Kyma dashboard

- config/ui-extensions/kedas/general
- Use the full phrase instead of the abbreviation
https://github.com/kyma-project/kyma/issues/18321
> Unify Keda CR description

- keda.yaml
- sec-scanners-config.yaml
> Bump keda to 2.14

- config/default/kustomization.yaml
- config/manager/manager.yaml
- config/priority-class/keda_priority_class.yaml
- config/priority-class/kustomization.yaml
- Add Keda priority class
- #447
> Add Keda priority class

- docs/contributor/04-10-testing-strategy.md
> Fix link to mlc config

- config/default/kustomization.yaml
- config/ui-extensions/kedas/kustomization.yaml
- Use consistent labels
- https://github.com/kyma-project/serverless/issues/1014
> Use consistent labels

- config/default/kustomization.yaml
- config/manager/manager.yaml
- label selectors are immutable, they cannot be changed without deleting deployment completely
- https://github.com/kyma-project/serverless/issues/1014
> restore old label selector

- config/manager/manager.yaml
- config/priority-class/keda_priority_class.yaml
- pkg/reconciler/fsm.go
- pkg/reconciler/update_objects.go
- add priority class name for all managed keda workloads
#447
> Add priority class for managed keda workloads

- .github/workflows/keda-build-pull.yaml
- .github/workflows/keda-build-push.yaml
- .github/workflows/keda-build-release.yaml
- .github/workflows/upgrade-tests.yaml
- Add GHA build workflows
- #456
> Add GHA build workflows

- .github/workflows/keda-build-push.yaml
- Add branch name tag to push image
- #459
> Add branch name tag to push image

- .github/workflows/keda-build-push.yaml
> Fix tag creation

- Dockerfile
- allow building our image
- https://github.com/kyma-project/serverless/issues/942
> Use synced image in the operators Dockerfile

- docs/contributor/01-20-extend-ui.md
- docs/contributor/04-20-lifecycle-management.md
- examples/redis-scaler/README.md
> Change enable and disable to add and delete in the Keda repo

- docs/contributor/04-10-testing-strategy.md
- Adjust testing-strategy CI jobs and links
#464
> Adjust testing-strategy

- .github/workflows/create-release.yaml
- Change `_build-push` to `_build` action in `create-release`
#466
> Fix create release by using correct build job

- .github/workflows/create-release.yaml
- Pass tag to `_build` workflow
#466
> Fix builds step in create-release workflow

- keda.yaml
- sec-scanners-config.yaml
> Bump keda to 2.15.1

- go.mod
- go.sum
- pkg/reconciler/fsm_test.go
> Add basic label test

- .github/actions/setup-go/action.yaml
- Use go.mod go version in actions
- https://github.com/kyma-project/serverless/issues/1034
> Use go.mod go version in actions

- .golangci.yaml
- test/hpa/verify.go
- Unify linter config
- https://github.com/kyma-project/serverless/issues/1038
> Unify linter config

- .golangci.yaml
- Lint tests
- https://github.com/kyma-project/serverless/issues/1038
> Lint tests

- Makefile
- Fix controller-gen version detection
> Fix controller-gen version detection

- config/ui-extensions/kedas/details
- config/ui-extensions/kedas/form
- support sidecar configuration in the Busola described by this [PR](https://github.com/kyma-project/keda-manager/pull/504)
- https://github.com/kyma-project/keda-manager/issues/501
> Add Istio Sidecar configuration to the UI panel

- docs/user/01-20-configuration.md
- document this [PR](https://github.com/kyma-project/keda-manager/pull/504)
- https://github.com/kyma-project/keda-manager/issues/501
> Update docs about sidecar injection

- config/ui-extensions/kedas/details
- display `False` when fields do not exist
> Improve istio injection summary

- api/v1alpha1/keda_types.go
- config/crd/bases/operator.kyma-project.io_kedas.yaml
- Add proper categories for CRDs according to linked ADR
- ...
- ...
- https://github.com/kyma-project/community/issues/912
> feat: Add proper categories for keda CRDs

- api/v1alpha1/keda_types.go
- config/crd/bases/operator.kyma-project.io_kedas.yaml
- Removed "kyma" category which caused conficts with the kyma "crd"
- ...
- ...
- https://github.com/kyma-project/community/issues/912
- https://github.com/kyma-project/keda-manager/pull/512
> feat: Add proper categories for CRDs

- .github/actions/setup-btp/action.yaml
- .github/actions/setup-kyma/action.yaml
- .github/actions/setup-terraform/action.yaml
- .github/workflows/_integration-tests.yaml
- .github/workflows/create-release.yaml
- test/btp/README.md
- test/btp/hack/Makefile
- test/btp/hack/get_btp_file_name.sh
- test/btp/hack/set-tf-envs.sh
- test/btp/tf/main.tf
- test/btp/tf/variables.tf
- test/main.go
- Add Keda integration test which runs on BTP as a part of release workflow
#511
> Btp integration test

- external-images.yaml
- Add image syncer config
- #523
> Add image syncer config

- hack/common/verify_keda_status.sh
> Fix status check

- test/main.go
- Remove checking if hpa was deleted from integration test scenario
#511
> Remove checking if hpa was deleted from integration test scenario

- .github/workflows/create-release.yaml
- hack/replace_keda_crd_version.sh
As in title
https://github.com/kyma-project/keda-manager/issues/453
> Bump CRD Version during release

- .github/workflows/create-release.yaml
- .github/workflows/metrics.yaml
- replace non-whitelisted action with regular curl
Reverting https://github.com/kyma-project/keda-manager/pull/290
> Re-enable Dora insights binary

- .github/workflows/metrics.yaml
> Fix Dora insights binary download

- .github/workflows/metrics-test.yaml
- .github/workflows/test-dora-download.yaml
> test dora download

- .github/workflows/_metrics.yaml
> Change deployment target for Dora stats

- .github/actions/create-k3d-cluster/action.yaml
- Makefile
- config/crd/bases/operator.kyma-project.io_kedas.yaml
> Bump k8s version

- .github/workflows/_integration-tests.yaml
- use latest tf gh action sha to include https://github.com/kyma-project/terraform-module/pull/66
> Bump tf modules to include module json parsing

- .github/workflows/promote-to-release-channel.yaml
- Makefile
- module-config-template.yaml
- Introduce promotion workflow
Unification of CD for all kyma modules maintained by @kyma-project/otters
> Automate Keda module promotion flow

- Dockerfile
> Bump base go image

- external-images.yaml
> bump keda images

- .github/workflows/create-release.yaml
> Remove unused release step

- config/ui-extensions/scaledobjects/list
- controllers/keda_controller_rbacs.go
- keda.yaml
- sec-scanners-config.yaml
> Bump Keda to 2.16.1

- .github/workflows/_integration-tests.yaml
> Bump actions used for kyma terraforming in integration tests

- examples/redis-scaler/README.md
> Fix a link

- config/default/kustomization.yaml
- https://github.com/kyma-project/keda-manager/issues/571
> Change module name label

- .github/scripts/upgrade-operator-kustomize.sh
- config/manager/manager.yaml
- config/rbac/role.yaml
- pkg/reconciler/apply.go
- pkg/reconciler/fsm.go
- pkg/reconciler/fsm_test.go
- set common labels for all keda resources (installed)
- https://github.com/kyma-project/keda-manager/issues/571
> Set labels for all installed module resources

- config/manager/manager.yaml
- format file using the `yq -i '.' config/manager/manager.yaml` to not generate too many changes on release where we use the `yq` app on this file
> Format the manager.yaml

- config/default/kustomization.yaml
- propagate common labels to templates
- https://github.com/kyma-project/keda-manager/issues/571
> Propagate manager labels to templates

- .github/workflows/push.yaml
- .github/workflows/release.yaml
> fix build job permissions

- Makefile
- hack/keda_values.yaml
- keda.yaml
- tempalte keda manifest with metrics enabled
**Issue:**
- https://github.com/kyma-project/kyma/issues/18784
> Enable `prometheus` metrics

- docs/contributor/03-10-scripts-not-working.md
> Replace Remedy with Solution

- external-images.yaml
> Sync kedacore 2.17

- api/v1alpha1/keda_types.go
- hack/keda_values.yaml
- keda.yaml
> Bump minimum TLS version to 1.3

- hack/keda_values.yaml
- keda.yaml
- generate keda deployment with image pull policy set to `IfNotPresent`
Fixes #420
> Set ImagePullPolicy to IfNotPresent

- examples/keda-cpu-scaler-demo.yml
- use httpbin image for cpu scaling demonstration
Fixes  #591
> Replace order-service with httpbin

- sec-scanners-config.yaml
> manually bump sec-scanner-config

- sec-scanners-config.yaml
- Update keda image versions in scanner config
https://github.com/kyma-project/keda-manager/issues/615
> Bump keda images in sec-scanner-config

- docs/user/01-20-configuration.md
- Explain how to use custom minimum TLS version for keda
#616
> Document how to override Keda Minimum allowed TLS version

- api/v1alpha1/keda_types.go
- docs/user/01-20-configuration.md
- hack/keda_values.yaml
- keda.yaml
- cherry-pick https://github.com/kyma-project/keda-manager/pull/626
> Restore Min TLS 1.2 as default (#626)

- .github/workflows/lint.yaml
- .golangci.yaml
- pkg/reconciler/apply.go
- pkg/reconciler/delete_resources.go
> bump linter

- Dockerfile
> bump base Go images

- .github/workflows/_build.yaml
- Dockerfile
- make sure all layers containing the go build command has the `--platform=$BUILDPLATFORM` flag and `GOOS=$TARGETOS GOARCH=$TARGETARCH` envs
- https://github.com/kyma-project/keda-manager/issues/638
> Build multi-arch images

- api/v1alpha1/keda_types.go
- config/crd/bases/operator.kyma-project.io_kedas.yaml
- config/priority-class/keda_priority_class.yaml
- pkg/reconciler/fsm.go
- pkg/reconciler/fsm_test.go
- pkg/reconciler/verify.go
- inform user about the installed Keda version
- set proper version label on Keda resources (do not overwrite it)
- https://github.com/kyma-project/keda-manager/issues/622#issue-3045901017
> Extend Keda CR with the `kedaVersion` field

- .github/scripts/upgrade-sec-scanners-config.sh
- .github/workflows/promote-to-release-channel.yaml
Unblocks new submission pipeline
> Fix bumping BDBA during patch releases

- external-images.yaml
> bump base keda images

- .github/scripts/upgrade-sec-scanners-config.sh
- we should only bump keda-manager tag... not the tags of keda images
> Fix img tag updating script

- .github/actions/create-k3d-cluster/action.yaml
- Makefile
- Bump kubernetes version for k3d-based integration tests
> Bump k8s version for K3D tests

- .github/workflows/_integration-tests.yaml
- Use latest from kyma's terrafor module gh actions
https://github.com/kyma-project/terraform-btp-kyma-environment/releases/tag/1.0.0
> Bump terraform module gh actions

- Dockerfile
- main.go
- adjust base images
- compile and run executables with proper FIPS flags
- use `scratch` as a base image
- #688
> use base FIPS alpine images
