- Makefile
- README.md
- config/default/kustomization.yaml
- keda component should be named with `kyma-project.io`
> Fix keda module name prefix

- .gitignore
- Makefile
- config/manager/kustomization.yaml
- hack/ci/Makefile
- add make target to render keda manager manifest yaml file. Such target is quite handy in generating `keda-manager.yaml` release artifact
see [here](https://github.com/kyma-project/keda-manager/releases/tag/v0.0.1)
> Add make target to render keda-manager manifest

- Dockerfile
- use latest golang to mitigate protecode findings
https://github.com/kyma-project/keda-manager/issues/10
> Use latest golang in builder image

- Dockerfile
- Bump golang runtime to exclude potential vulnerabilities
CVE-2023-24540, CVE-2023-29400, CVE-2023-24539
> Bump golang-runtime to 1.20.4

- config/ui-extensions/scaledobjects/general
- No helm templating is involved in keda installation - the extra escaping is not needed (as it causes errors in the UI)
> Remove helm escaping in UI config

- config/ui-extensions/scaledobjects/details
- config/ui-extensions/scaledobjects/list
- In Keda 2.10.x the `Deployment` is a default scaledTargetREf.kind and in this case its not rendered in the spec. Fix UI for such case
> Assume Deployment as a default scaledTargetRef.kind

- keda.yaml
- sec-scanners-config.yaml
- reference kyeda images from `europe-docker.pkg.dev/kyma-project` in the keda manifest
- change images in the security scanners config
#157
> Use keda images synced into europe-docker.pkg.dev/kyma-project

- config/manager/manager.yaml
- Define requested resources and limits so that k8s would use guaranteed qos service class
Fixes #173
> Define resources for keda-manager workload

- scripts/create_changelog.sh
- Commits made by kyma-bot are no longer saved in changelog
> Do not save kyma-bot commits in the changelog

- hack/common/Makefile
- spec.target is gone in v1beta2 version of moduletemplate
- change the name of the moduletemplate to the same one used in release channels
> Fix integration tests

- Dockerfile
- Use latest version of golang-runtime
> Bump golang-runtime to 1.20.5

- scripts/check_image.sh
If the pull request requires a decision, follow the [decision-making process](https://github.com/kyma-project/community/blob/main/governance.md) and replace the PR template with the [decision record template](https://github.com/kyma-project/community/blob/main/.github/ISSUE_TEMPLATE/decision-record.md).
-->
check in `check_image.sh` also if the date is correct (besides of commit hash)
- check in `check_image.sh` also if the date is correct (besides of commit hash)
https://github.com/kyma-project/keda-manager/issues/227
> Check also the date in the image

- keda.yaml
- Keda workloads should not have istio carts injected. Bringing back the istio labels after keda 2.11.1 bump
#237
> Remove istio side-car from keda workloads

- .github/workflows/create-release.yaml
- sec-scanners-config.yaml
- temporarily skip publishing release metrics to DORA to unblosk create-release workflow
#272
> Skip DORA metrics step

- .reuse/dep5
- Dockerfile
- sec-scanners-config.yaml
- Use latest versin of golang in builder image
- Fill in upstream contact info
- bump sec scanner config
> Bump Golang img version (1.21.0)

- api/v1alpha1/keda_types.go
- pkg/reconciler/delete_resources.go
- pkg/reconciler/delete_resources_test.go
When user intervention is needed, status of the module should be set to Warning.
https://github.com/kyma-project/serverless-manager/issues/259
https://github.com/kyma-project/lifecycle-manager/issues/525
> Set Warning state when orphaned CRs found at deletion

- module-config-template.yaml
- include doc url and github repo url
https://github.com/kyma-project/keda-manager/issues/267
> Include docu link and repo url in module-config template

- scripts/check_release_tag.sh
- drop 'v' prefix from keda module version
> Drop v prefix from version format

- Makefile
- module-config-template.yaml
- we should not use sec-scanners-config to build moduletemplate because this config is used only to scan moduletemplate on production (this does not happen in this repo). In this repo, we should only test the integration and prepare ready to build module
- https://github.com/kyma-project/serverless/issues/411
> Don't use sec-scanners-config to build moduletemplate on pre/post submit

- main.go
Exclude secrets and config maps from being auto-loaded to controllers cache
- Remove secrets and configmaps from the cache
#333
> Remove secrets and configmaps from the cache
